name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: "-Xmx5120m -XX:+UnlockExperimentalVMOptions"
      GRADLE_OPTS: "-Xms1g -Xmx5120m -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process"

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3
      - name: Install JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Configure Gradle
        run: ./gradlew help
      - name: Build project
        run: ./gradlew assemble testDebugUnitTest --stacktrace
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2.2.2
        with:
          name: test-reports
          path: ./app/build/reports
