name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: "-XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC -Dorg.gradle.jvmargs='-Xmx4g -Xms1g -XX:MaxMetaspaceSize=1g' -Dfile.encoding=UTF-8 -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Configure Gradle
        run: ./gradlew help
      - name: Build project
        run: ./gradlew assemble testDebugUnitTest --stacktrace
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: app/build/reports
      - name: Upload release APK
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: app/build/outputs/apk/release
